### ISSUE TITLE
Cannot find module 'map-assign' if loaded on startup

### ISSUE THREAD

**Issue by thewrongjames** [thewrongjames/really-black-ui#1]
The theme throws the below error if atom attempts to load it on startup, but not when switching to it once atom has been loaded. Possibly connected is the fact that the tabs and text editor background do not display properly on startup of atom with the them loaded, but are fine on loading the theme after startup.

Steps to reproduce:

1. Start atom with really-black-ui as selected theme.

**Atom**: 1.23.3 x64
**Electron**: 1.7.11
**OS**: linux 4.14.15-1-ARCH
**Thrown From**: [really-black-ui](https://github.com/matthewlucock/atom-really-black-ui) package 0.0.0

### Stack Trace

Failed to activate the really-black-ui package

```
At Cannot find module 'map-assign'

Error: Cannot find module 'map-assign'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:350:52)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/james/really-black-ui/scripts/configObserverCallbacks.js:3:19)
    at Object.<anonymous> (/home/james/really-black-ui/scripts/configObserverCallbacks.js:43:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/james/really-black-ui/scripts/main.js:3:33)
    at Object.<anonymous> (/home/james/really-black-ui/scripts/main.js:47:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at ThemePackage.module.exports.Package.requireMainModule (/usr/lib/atom/src/package.js:935:29)
    at ThemePackage.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:242:16)
    at measure (/usr/lib/atom/src/theme-package.js:45:18)
    at ThemePackage.module.exports.Package.measure (/usr/lib/atom/src/package.js:97:15)
    at activationPromise.Promise (/usr/lib/atom/src/theme-package.js:42:14)
    at Promise (<anonymous>)
```

### Commands

```
```

### Non-Core Packages

```
atom-dracula-black 0.3.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.1 
black-ui 0.3.5 
black-v-syntax 0.2.1 
build 0.70.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.6 
city-lights-ui 1.3.1 
fonts 3.0.3 
git-plus 7.10.0 
highlight-selected 0.13.1 
language-archlinux 0.9.2 
language-pug 0.0.21 
language-underscore 0.0.0 
language-unix-shell 0.40.1 
markdown-writer 2.7.3 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
pug 0.8.0 
rad-syntax 0.4.0 
really-black-ui 0.0.0 
script 3.17.3 
```

**Comment by thewrongjames** [comment]
Turns out I didn't install any of the dependancies, largely because I have no idea what I am doing. Running `npm install` in the root of the repository fixed this, but the fact that the theme worked fine when loaded after atom still confuses me. Anyway, it works now, and this fork is looking a little silly.
